FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json angular.json tsconfig.json tsconfig.app.json tsconfig.spec.json ./
COPY .browserslistrc .postcssrc.json tailwind.config.js ./
COPY public ./public
COPY src ./src

RUN npm ci
RUN npm run build -- --configuration production

FROM nginx:1.27-alpine

COPY --from=builder /app/dist/Miam-DV/browser /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
