FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json angular.json tsconfig.json tsconfig.app.json tsconfig.spec.json ./
COPY .browserslistrc .postcssrc.json tailwind.config.js ./
COPY public ./public
COPY src ./src

RUN npm ci
RUN npm run build -- --configuration production

FROM caddy:2-alpine

WORKDIR /srv
COPY --from=builder /app/dist/Miam-DV/browser ./
COPY Caddyfile /etc/caddy/Caddyfile

EXPOSE 80
