FROM node:24-alpine AS builder

WORKDIR /app

RUN npm install --global pnpm@11.24.0

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml angular.json tsconfig.json tsconfig.app.json tsconfig.spec.json ./
COPY .postcssrc.json tailwind.config.js ./
COPY public ./public
COPY src ./src

RUN pnpm install --frozen-lockfile
RUN pnpm build --configuration production

FROM nginx:1.30-alpine AS runner

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/Miam-DV/browser /usr/share/nginx/html

EXPOSE 4000

CMD ["nginx", "-g", "daemon off;"]
